# vim:set ft=tmux:
# --> Catppuccin Dracula
set -ogq @thm_bg "#1D1A1E"
set -ogq @thm_fg "#cdd6f4"
# Colors
set -ogq @thm_rosewater "#f79bda"
set -ogq @thm_flamingo "#ff9bba"
set -ogq @thm_pink "#F07DC8"
set -ogq @thm_mauve "#CAA9FA"
set -ogq @thm_red "#f38ba8"
set -ogq @thm_maroon "#ff9bba"
set -ogq @thm_peach "#f9e2af"
set -ogq @thm_yellow "#f9e2af"
set -ogq @thm_green "#7DF0A5"
set -ogq @thm_teal "#7BD2FF"
set -ogq @thm_sky "#99e0ff"
set -ogq @thm_sapphire "#7BD2FF"
set -ogq @thm_blue "#CAA9FA"
set -ogq @thm_lavender "#d4b9ff"
# Surfaces and overlays
set -ogq @thm_subtext_1 "#a6adc8"
set -ogq @thm_subtext_0 "#bac2de"
set -ogq @thm_overlay_2 "#9399b2"
set -ogq @thm_overlay_1 "#7f849c"
set -ogq @thm_overlay_0 "#6c7086"
set -ogq @thm_surface_2 "#585b70"
set -ogq @thm_surface_1 "#45475a"
set -ogq @thm_surface_0 "#313244"
set -ogq @thm_mantle "#181825"
set -ogq @thm_crust "#11111b"
